name: Java test JUnit

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configurar JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Compilar y ejecutar pruebas JUnit
        run: mvn -B clean test

      - name: Subir reportes de pruebas como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: reporte-junit
          path: target/surefire-reports/
